#!/usr/bin/with-contenv bash



UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"


# NOTE : we do not use hotreload option on webhook, (https://github.com/almir/docker-webhook)
#       because we dont need it AND because it throw an arror
#           2021-02-05T02:31:40.705054794Z [webhook] 2021/02/05 03:31:40 setting up file watcher for /etc/webhook/hooks.json
#           2021-02-05T02:31:40.705071108Z [webhook] 2021/02/05 03:31:40 error adding hooks file to the watcher
#           2021-02-05T02:31:40.705090153Z no space left on device
#       which is relative to fsnotify go lib https://github.com/fsnotify/fsnotify/blob/7f4cf4dd2b522a984eaca51d1ccee54101d3414a/README.md which may have problem with this feature depending on the OS

#exec \
#    s6-setuidgid abc /app/webhook -verbose -hooks=/etc/webhook/hooks.json -hotreload
exec \
    s6-setuidgid abc /app/webhook -verbose -hooks=/etc/webhook/hooks.json
