volumes:
  kcc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${KCC_DATA_PATH}
    name: ${TANGO_APP_NAME}_kcc_data

services:
  # Kindle Comic Converter is a Python app to convert comic/manga files or folders to EPUB, Panel View MOBI or E-Ink optimized CBZ.
  # NOTE : VNC port is not open here
  # https://github.com/ciromattia/kcc
  # https://github.com/StudioEtrange/kcc
  kcc:
    image: studioetrange/kcc:latest
    container_name: ${TANGO_APP_NAME}_kcc
    depends_on:
      - service_init
    restart: unless-stopped
    volumes:
      # will contain kcc configuration
      - kcc_data:/config
      # different paths used by kcc
      - download:/download
      - calibredb_books_media:/calibredb/books
      - calibredb_press_media:/calibredb/press
      - calibredb_pgames_media:/calibredb/pgames
    environment:
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
      - KCC_VERSION=${KCC_VERSION}
      - REPO_GIT=${KCC_REPO_GIT}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : kcc
      - "traefik.http.services.kcc.loadbalancer.server.port=8080"
      - "traefik.http.services.kcc.loadbalancer.server.scheme=http"
      - "traefik.http.services.kcc.loadbalancer.passhostheader=true"
      # middlewares : kcc
      # service router : kcc
      - "traefik.http.routers.kcc.entrypoints=${KCC_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.kcc.rule=HostRegexp(`{subdomain:${KCC_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.kcc.priority=${KCC_PRIORITY}"
      - "traefik.http.routers.kcc.service=kcc"
      - "traefik.http.routers.kcc-secure.entrypoints=${KCC_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.kcc-secure.rule=HostRegexp(`{subdomain:${KCC_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.kcc-secure.priority=${KCC_PRIORITY}"
      - "traefik.http.routers.kcc-secure.service=kcc"
      - "traefik.http.routers.kcc-secure.tls=true"
      - "traefik.http.routers.kcc-secure.tls.domains[0].main=${KCC_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : kcc
      #- "traefik.http.routers.kcc.middlewares=kcc-auth@rest,error-middleware"
      #- "traefik.http.routers.kcc-secure.middlewares=kcc-auth@rest,error-middleware"
      - "traefik.http.routers.kcc.middlewares=error-middleware"
      - "traefik.http.routers.kcc-secure.middlewares=error-middleware"
    networks:
      - default
    expose:
      - 8080/tcp
    build:
      context: https://github.com/StudioEtrange/docker-kcc.git
