#!/usr/bin/env bash

# DEPRECATED replaced by a docker service

# FEATURES : nzbToMedia is a script used to postprocess download between sabnzbd and indexer like sickbeard
#            this plugin install nzbToMedia in /data/nzbtomedia

# NOTE :
# Error AttributeError 'module' object has no attribute 'InitialSchema'
# https://github.com/clinton-hall/nzbToMedia/issues/1614
# cd "${DATA}"
# python -c "import cleanup; cleanup.force_clean_folder('libs', cleanup.FOLDER_STRUCTURE['libs'])"
# python -c "import cleanup; cleanup.force_clean_folder('core', cleanup.FOLDER_STRUCTURE['core'])"


# load tango libs
for f in /pool/tango/libs/*; do
	[ -f "${f}" ] && . ${f}
done
# load app libs
[ ! "${TANGO_NOT_IN_APP}" = "1" ] && for f in /pool/${TANGO_APP_NAME}/libs/*.sh; do [ -f "${f}" ] && . ${f}; done


PLUGIN="nzbtomedia"
[ "$NZBTOMEDIA_VERSION" = "" ] && VERSION="12.1.04" || VERSION="$1"
DATA="/data/${PLUGIN}/${VERSION}"

echo "* Plugin : ${PLUGIN} ${VERSION}"

echo "L-- STEP : install plugin"
if find "${DATA}" -mindepth 1 2>/dev/null | read; then
    echo "  + ${PLUGIN} already installed in ${DATA}"
else
    mkdir -p "${DATA}"
    type curl 1>&2 2>/dev/null && {
        curl -fkSL -o "/tmp/${PLUGIN}-${VERSION}.tar.gz" "https://github.com/clinton-hall/nzbToMedia/archive/${VERSION}.tar.gz"
    } || {
        wget "https://github.com/clinton-hall/nzbToMedia/archive/${VERSION}.tar.gz" -O "/tmp/${PLUGIN}-${VERSION}.tar.gz" --no-check-certificate
    }

    cd "${DATA}"
    tar xzf "/tmp/${PLUGIN}-${VERSION}.tar.gz" --strip-components=1
    # TODO : generate autoProcessMedia.cf
    cp "${DATA}/autoProcessMedia.cfg.spec" "${DATA}/autoProcessMedia.cfg"

    # add a sh launcher to force use of python3
    # NOTE : for python3 make a launcher for nzbToSickbeard because sabnzbd use python2 and we want nzbToSickBeard use python3
    tee "${DATA}/nzbToSickBeard.sh" << END
#!/bin/bash
_CURRENT_FILE_DIR="\$( cd "\$( dirname "\${BASH_SOURCE[0]}" )" && pwd )"
python3 \${_CURRENT_FILE_DIR}/nzbToSickBeard.py "\$@"
END
    chmod +x "${DATA}/nzbToSickBeard.sh"

fi
echo "L-- STEP : setup plugin"
echo "  -"

echo "L-- STEP : run plugin"
echo "  -"

echo "L-- STEP : end plugin"