#!/usr/bin/env bash


# FEATURES : will set remote transmission port


# NEED transmission volumes
# NEED lib pia port forward
# WAIT for vpn and transmission service up

# load tango libs
for f in /pool/tango/libs/*; do
	[ -f "${f}" ] && . ${f}
done
# load app libs
[ ! "${TANGO_NOT_IN_APP}" = "1" ] && for f in /pool/${TANGO_APP_NAME}/libs/*.sh; do [ -f "${f}" ] && . ${f}; done


PLUGIN="transmission_pia_port"
DATA="/plugins_data/${PLUGIN}"

echo "* Plugin : ${PLUGIN}"

echo "L-- STEP : install plugin"
echo "  -"
echo "L-- STEP : setup plugin"
echo "  -"
echo "L-- STEP : run plugin"

# ask PIA vpn provider to forward a port
pia_get_port "${DATA}"
if [ $? -eq 0 ]; then
	echo "  - we use port $PIA_FORWARD_PORT, setting transmission with it"
	# set transmission with this port
 	transmission_set_port "$PIA_FORWARD_PORT"
else
	echo "  - ERROR while getting PIA port"
fi


echo "L-- STEP : end plugin"
