
volumes:
  web2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEB2_PATH}
    name: ${TANGO_APP_NAME}_web2_data

services:
  
  web2:
    image: httpd:${WEB2_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_web2
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - web2_data:/usr/local/apache2/htdocs
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.web2.entrypoints=${WEB2_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.web2.rule=HostRegexp(`{subdomain:web2}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.web2.priority=${WEB2_PRIORITY}"
      - "traefik.http.routers.web2.service=web2"
      - "traefik.http.routers.web2-secure.entrypoints=${WEB2_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.web2-secure.rule=HostRegexp(`{subdomain:web2}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.web2-secure.priority=${WEB2_PRIORITY}"
      - "traefik.http.routers.web2-secure.service=web2"
      - "traefik.http.routers.web2-secure.tls=true"
      - "traefik.http.routers.web2-secure.tls.domains[0].main=web2.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.web2.loadbalancer.server.port=80"
      - "traefik.http.services.web2.loadbalancer.server.scheme=http"
      - "traefik.http.services.web2.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 80

  whoami:
    image: containous/whoami:${WHOAMI_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_whoami
    depends_on: 
      - service_init
    restart: unless-stopped
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=${WHOAMI_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.whoami.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami.priority=${WHOAMI_PRIORITY}"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami-secure.entrypoints=${WHOAMI_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.whoami-secure.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami-secure.priority=${WHOAMI_PRIORITY}"
      - "traefik.http.routers.whoami-secure.service=whoami"
      - "traefik.http.routers.whoami-secure.tls=true"
      - "traefik.http.routers.whoami-secure.tls.domains[0].main=whoami.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 80



  # https://github.com/jlesage/docker-firefox
  firefox:
    image: jlesage/firefox:${FIREFOX_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_firefox
    depends_on: 
      - service_init
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=${FIREFOX_WIDTH}
      - DISPLAY_HEIGHT=${FIREFOX_HEIGHT}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.firefox.entrypoints=${FIREFOX_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.firefox.rule=HostRegexp(`{subdomain:firefox}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox.priority=${FIREFOX_PRIORITY}"
      - "traefik.http.routers.firefox.service=firefox"
      - "traefik.http.routers.firefox-secure.entrypoints=${FIREFOX_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.firefox-secure.rule=HostRegexp(`{subdomain:firefox}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox-secure.priority=${FIREFOX_PRIORITY}"
      - "traefik.http.routers.firefox-secure.service=firefox"
      - "traefik.http.routers.firefox-secure.tls=true"
      - "traefik.http.routers.firefox-secure.tls.domains[0].main=firefox.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.firefox.loadbalancer.server.port=5800"
      - "traefik.http.services.firefox.loadbalancer.server.scheme=http"
      - "traefik.http.services.firefox.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 5000
    