
volumes:
  web2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DATA_PATH}/${WEB2_ROOT_FOLDER}
    name: ${TANGO_APP_NAME}_web2_data
  transmission_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DATA_PATH}/transmission_data
    name: ${TANGO_APP_NAME}_transmission_data
  transmission_download:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DATA_PATH}/transmission_download
    name: ${TANGO_APP_NAME}_transmission_download
  transmission_watch:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DATA_PATH}/transmission_watch
    name: ${TANGO_APP_NAME}_transmission_watch


services:
  
  web2:
    image: httpd:${WEB2_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_web2
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - web2_data:/usr/local/apache2/htdocs
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.web2.entrypoints=${WEB2_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.web2.rule=HostRegexp(`{subdomain:web2}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.web2.priority=${WEB2_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.web2.service=web2"
      - "traefik.http.routers.web2-secure.entrypoints=${WEB2_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.web2-secure.rule=HostRegexp(`{subdomain:web2}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.web2-secure.service=web2"
      - "traefik.http.routers.web2-secure.tls=true"
      - "traefik.http.routers.web2-secure.tls.domains[0].main=web2.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.web2.loadbalancer.server.port=80"
      - "traefik.http.services.web2.loadbalancer.server.scheme=http"
      - "traefik.http.services.web2.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 80

  whoami:
    image: containous/whoami:${WHOAMI_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_whoami
    depends_on: 
      - service_init
    restart: unless-stopped
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=${WHOAMI_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.whoami.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami.priority=${WWHOAMI_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami-secure.entrypoints=${WWHOAMI_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.whoami-secure.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami-secure.service=whoami"
      - "traefik.http.routers.whoami-secure.tls=true"
      - "traefik.http.routers.whoami-secure.tls.domains[0].main=whoami.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 80



  # https://github.com/jlesage/docker-firefox
  firefox:
    image: jlesage/firefox:${FIREFOX_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_firefox
    depends_on: 
      - service_init
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=${FIREFOX_WIDTH}
      - DISPLAY_HEIGHT=${FIREFOX_HEIGHT}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.firefox.entrypoints=${FIREFOX_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.firefox.rule=HostRegexp(`{subdomain:firefox}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox.priority=${FIREFOX_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.firefox.service=firefox"
      - "traefik.http.routers.firefox-secure.entrypoints=${FIREFOX_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.firefox-secure.rule=HostRegexp(`{subdomain:firefox}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox-secure.service=firefox"
      - "traefik.http.routers.firefox-secure.tls=true"
      - "traefik.http.routers.firefox-secure.tls.domains[0].main=firefox.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.firefox.loadbalancer.server.port=5800"
      - "traefik.http.services.firefox.loadbalancer.server.scheme=http"
      - "traefik.http.services.firefox.loadbalancer.passhostheader=true"
    networks:
      - default
    #network_mode: "service:vpn"
    expose:
      - 5000
    
  # https://github.com/linuxserver/docker-transmission
  transmission:
    image: linuxserver/transmission:${TRANSMISSION_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_transmission
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - transmission_download:/config
      - transmission_data:/downloads
      - transmission_watch:/watch
    environment:
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
      # Specify an alternative UI options are /combustion-release/, /transmission-web-control/, and /kettu/
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=${TRANSMISSION_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.transmission.rule=HostRegexp(`{subdomain:transmission}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.transmission.priority=${TRANSMISSION_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.routers.transmission-secure.entrypoints=${TRANSMISSION_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.transmission-secure.rule=HostRegexp(`{subdomain:transmission}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.transmission-secure.service=transmission"
      - "traefik.http.routers.transmission-secure.tls=true"
      - "traefik.http.routers.transmission-secure.tls.domains[0].main=transmission.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.services.transmission.loadbalancer.server.scheme=http"
      - "traefik.http.services.transmission.loadbalancer.passhostheader=true"
    networks:
       - default
    #network_mode: "service:vpn"
    expose:
      - 9091/tcp
      - 51413/tcp
      - 51413/udp
    ports:
      - ${TRANSMISSION_PORT}:51413/tcp
      - ${TRANSMISSION_PORT}:51413/udp