#########################################################################
# Title:         Cloudbox: SABnzbd Role                                 #
# Author(s):     desimaniac                                             #
# Modified by :  StudioEtrange
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/sabnzbd                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- debug: 
    msg: 
      - "SABNZBD_DATA_PATH: {{ lookup('env','SABNZBD_DATA_PATH') }}"
      - "SABNZBD_INI_PATH: {{ lookup('env','SABNZBD_INI_PATH') }}"

- name: Register sabnzbd_ini
  stat:
    path: "{{ sabnzbd.ini }}"
  register: sabnzbd_ini

- name: Settings Tweaks
  include_tasks: "subtasks/sabnzbd_settings.yml"
  when: sabnzbd_ini.stat.exists