version: '2.4'

networks:
  default:
    name: ${TANGO_APP_NETWORK_NAME}

volumes:
  # volumes specific for each app
  artefact:
    name: ${TANGO_APP_NAME}_artefact
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_DATA_PATH}
    name: ${TANGO_APP_NAME}_data
  plugins_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PLUGINS_DATA_PATH}
    name: ${TANGO_APP_NAME}_plugins_data
  # volumes that can be shared between each app
  internal_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TANGO_DATA_PATH}
    name: ${TANGO_INSTANCE_NAME}_internal_data
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TANGO_DATA_PATH}/letsencrypt
    name: ${TANGO_INSTANCE_NAME}_letsencrypt
  traefikconfig:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TANGO_DATA_PATH}/traefikconfig
    name: ${TANGO_INSTANCE_NAME}_traefikconfig

# See detail variable here : https://github.com/StudioEtrange/openvpn-client
# NOTE : cap_add, security_opt are required for this image to function
x-vpn: &default-vpn
  image: studioetrange/openvpn-client:dev
  # need root to launch openvpn-client
  user: 0:0
  depends_on: 
    - service_init
  restart: unless-stopped
  # allow host net stack management
  cap_add:
    - NET_ADMIN
  # disable all SELinux policies 
  security_opt:
    - label:disable
  devices:
    - /dev/net/tun
  env_file:
    - ${GENERATED_ENV_FILE_FOR_COMPOSE}
  environment:
    # forbid any output network trafic outside VPN - usefull when VPN do not want to connect
    - FIREWALL=1
    # group id that will own openvpn-client process AND that can bypass any firewall rule
    - GROUPID=33333
    - 'OTHER_ARGS=--redirect-gateway def1'
  labels:
    - "${TANGO_INSTANCE_NAME}.managed=true"
  networks:
    - default
  build:
    context: https://github.com/StudioEtrange/openvpn-client.git#dev


services:

  # Launch all services
  tango:
    image: ${TANGO_SHELL_IMAGE}
    container_name: ${TANGO_APP_NAME}
    user: ${TANGO_USER_ID:-0}:${TANGO_GROUP_ID:-0}
    env_file:
      - ${GENERATED_ENV_FILE_FOR_COMPOSE}
    depends_on:
      - service_info
    networks:
      - default
    command: >
      bash -c "echo Hello ${TANGO_APP_NAME}."

  # do some init on internal volume
  # populate artefact named volume with a foo file because when mounting an empty named volume on {$TANGO_ARTEFACT_MOUNT_POINT}, it might get existing content if TANGO_ARTEFACT_MOUNT_POINT have content on host (i.e : cdrom, floppy, usb... for /media)
  volume_init:
    image: ${TANGO_SHELL_IMAGE}
    container_name: ${TANGO_INSTANCE_NAME}_volume_init
    user: root
    env_file:
      - ${GENERATED_ENV_FILE_FOR_COMPOSE}
    volumes:
      - artefact:/foo
    networks:
      - default
    command: >
      bash -c "touch /foo/.tango"  
      
  # init service
  service_init:
    image: ${TANGO_SHELL_IMAGE}
    container_name: ${TANGO_INSTANCE_NAME}_service_init
    user: ${TANGO_USER_ID:-0}:${TANGO_GROUP_ID:-0}
    depends_on:
      - volume_init
    volumes:
      - data:/data
      - internal_data:/internal_data
      #- artefact:${TANGO_ARTEFACT_MOUNT_POINT:-/artefact}
    env_file:
      - ${GENERATED_ENV_FILE_FOR_COMPOSE}
    networks:
      - default
    command: >
      bash -c "for f in /pool/tango/scripts_init/*; do [ -f \"$${f}\" ] && $${f}; done &&
      [ ! \"${TANGO_NOT_IN_APP}\" = "1" ] && for f in /pool/${TANGO_APP_NAME}/scripts_init/*; do [ -f \"$${f}\" ] && $${f}; done
      "

  # info on services
  service_info:
    image: ${TANGO_SHELL_IMAGE}
    container_name: ${TANGO_INSTANCE_NAME}_service_info
    user: ${TANGO_USER_ID:-0}:${TANGO_GROUP_ID:-0}
    env_file:
      - ${GENERATED_ENV_FILE_FOR_COMPOSE}
    networks:
      - default
    command: >
      bash -c "for f in /pool/tango/scripts_info/*; do [ -f \"$${f}\" ] && $${f}; done &&
      [ ! \"${TANGO_NOT_IN_APP}\" = "1" ] && for f in /pool/${TANGO_APP_NAME}/scripts_info/*; do [ -f \"$${f}\" ] && $${f}; done
      "


  # Launch all vpn
  vpn:
    image: ${TANGO_SHELL_IMAGE}
    container_name: ${TANGO_INSTANCE_NAME}_vpn
    user: ${TANGO_USER_ID:-0}:${TANGO_GROUP_ID:-0}
    depends_on:
      - service_init
    networks:
      - default
    command: >
      bash -c "echo Launching VPN."

  # OFELIA DOCS : https://github.com/mcuadros/ofelia/blob/master/docs/jobs.md
  # TO USE IT declare it in TANGO_SERVICES_DEFAULT and declare OFELIA_VERSION=v0.3.3
  # ofelia:
  #   image: mcuadros/ofelia:${OFELIA_VERSION:-v0.3.2}
  #   container_name: ${TANGO_INSTANCE_NAME}_ofelia
  #   user: 0:0
  #   restart: unless-stopped
  #   privileged: true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   labels:
  #     - "${TANGO_INSTANCE_NAME}.managed=true"
  #     - 'ofelia.job-local.ping-job.schedule=@every 5s'
  #     - 'ofelia.job-local.ping-job.command=ping'
  #   networks:
  #     - default
  #   command: >
  #     daemon --docker


  # Router
  # traefik launch order do not matter. It can be launched before or after all other services
  # ENTRYPOINT web_admin
  #     http://traefik.domain:${NETWORK_PORT_ADMIN}           => go to dashboard 
  #     http://traefik.domain:${NETWORK_PORT_ADMIN}/api
  #     http://traefik.domain:${NETWORK_PORT_ADMIN}/dashboard => go to dashboard
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: ${TANGO_INSTANCE_NAME}_traefik
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./traefik-conf.yml:/etc/traefik/traefik.yml
      - letsencrypt:/letsencrypt
      - traefikconfig:/traefikconfig
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # http://traefik.domain:${NETWORK_PORT_ADMIN} http://traefik.domain:${NETWORK_PORT_ADMIN}/api http://traefik.domain:${NETWORK_PORT_ADMIN}/dashboard
      - "traefik.http.routers.traefik_api.entrypoints=${TRAEFIK_ENTRYPOINTS:-web_admin}"
      # With traefik dashboard enabled, the router rule must catch requests for both /api and /dashboard
      - "traefik.http.routers.traefik_api.rule=HostRegexp(`{subdomain:${TRAEFIK_SUBDOMAIN}}{domain:${TANGO_DOMAIN:-.*}}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`) || PathPrefix(`/`))"
      - "traefik.http.routers.traefik_api.service=api@internal"
      - "traefik.http.routers.traefik_api.priority=${TRAEFIK_API_PRIORITY}"
      - "traefik.http.routers.traefik_api.middlewares=traefik_api-redirect,traefik_api-redirect2,error-middleware"

      - "traefik.http.routers.traefik_api-secure.entrypoints=${TRAEFIK_ENTRYPOINTS_SECURE:-web_admin_secure}"
      - "traefik.http.routers.traefik_api-secure.rule=HostRegexp(`{subdomain:${TRAEFIK_SUBDOMAIN}}{domain:${TANGO_DOMAIN:-.*}}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`) || PathPrefix(`/`))"
      - "traefik.http.routers.traefik_api-secure.service=api@internal"
      - "traefik.http.routers.traefik_api-secure.priority=${TRAEFIK_API_PRIORITY}"
      - "traefik.http.routers.traefik_api-secure.middlewares=traefik_api-redirect,traefik_api-redirect2,error-middleware"
      - "traefik.http.routers.traefik_api-secure.tls=true"
      - "traefik.http.routers.traefik_api-secure.tls.domains[0].main=${TRAEFIK_SUBDOMAIN}${TANGO_DOMAIN:-.*}"

      - "traefik.http.routers.traefik_api_rest.entrypoints=${TRAEFIK_ENTRYPOINTS:-web_admin}"      
      - "traefik.http.routers.traefik_api_rest.rule=HostRegexp(`{subdomain:${TRAEFIK_SUBDOMAIN}}{domain:${TANGO_DOMAIN:-.*}}`) && PathPrefix(`/api/providers/rest`)"
      - "traefik.http.routers.traefik_api_rest.service=rest@internal"
      - "traefik.http.routers.traefik_api_rest.priority=${TRAEFIK_API_REST_PRIORITY}"
      - "traefik.http.routers.traefik_api_rest.middlewares=traefik_api_rest-auth,error-middleware"
      
      - "traefik.http.routers.traefik_api_rest-secure.entrypoints=${TRAEFIK_ENTRYPOINTS_SECURE:-web_admin_secure}"
      - "traefik.http.routers.traefik_api_rest-secure.rule=HostRegexp(`{subdomain:${TRAEFIK_SUBDOMAIN}}{domain:${TANGO_DOMAIN:-.*}}`) && PathPrefix(`/api/providers/rest`)"
      - "traefik.http.routers.traefik_api_rest-secure.service=rest@internal"
      - "traefik.http.routers.traefik_api_rest-secure.priority=${TRAEFIK_API_REST_PRIORITY}"
      - "traefik.http.routers.traefik_api_rest-secure.middlewares=traefik_api_rest-auth,error-middleware"
      - "traefik.http.routers.traefik_api_rest-secure.tls=true"
      - "traefik.http.routers.traefik_api_rest-secure.tls.domains[0].main=${TRAEFIK_SUBDOMAIN}${TANGO_DOMAIN:-.*}"

      # redirect /dashboard to /dashboard/
      - "traefik.http.middlewares.traefik_api-redirect.redirectregex.regex=^(http[s]?://[^:/]+(:[0-9]+)?)/dashboard$$"
      - "traefik.http.middlewares.traefik_api-redirect.redirectregex.replacement=$${1}/dashboard/"
      # redirect / to /dashboard/
      - "traefik.http.middlewares.traefik_api-redirect2.redirectregex.regex=^(http[s]?://[^:/]+(:[0-9]+)?)(/)+$$"
      - "traefik.http.middlewares.traefik_api-redirect2.redirectregex.replacement=$${1}/dashboard/"

      # HTTP to HTTPS redirect routers - catch all request and redirect to secure entrypoint with HTTPS scheme if it is not the case
      # NOTE : we cannot use the method of set redirect middleware on each routers service because each service routers
      #        may have two entrypoints and middlewares dont know from which entrypoint the request come.
      #        So we use a global catch all router rule, using priority for exclude some services
      # NOTE : a redirect middleware will be dynamicly attached on each of these http-catchall-web_* routers
      # catch HTTP request on web_admin and web_admin_secure entrypoint
      - "traefik.http.routers.http-catchall-web_admin.entrypoints=web_admin,web_admin_secure"
      - "traefik.http.routers.http-catchall-web_admin.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_admin.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      # catch HTTPS request on web_admin only entrypoint (no need to catch HTTPS on web_admin_secure)
      - "traefik.http.routers.http-catchall-web_admin_secure.entrypoints=web_admin"
      - "traefik.http.routers.http-catchall-web_admin_secure.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_admin_secure.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      - "traefik.http.routers.http-catchall-web_admin_secure.tls=true"
      # catch HTTP request on web_secondary and web_secondary_secure entrypoint
      - "traefik.http.routers.http-catchall-web_secondary.entrypoints=web_secondary,web_secondary_secure"
      - "traefik.http.routers.http-catchall-web_secondary.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_secondary.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      # catch HTTPS request on web_secondary only entrypoint (no need to catch HTTPS on web_secondary_secure)
      - "traefik.http.routers.http-catchall-web_secondary_secure.entrypoints=web_secondary"
      - "traefik.http.routers.http-catchall-web_secondary_secure.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_secondary_secure.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      - "traefik.http.routers.http-catchall-web_secondary_secure.tls=true"
      # catch HTTP request on web_main and web_main_secure entrypoint
      - "traefik.http.routers.http-catchall-web_main.entrypoints=web_main,web_main_secure"
      - "traefik.http.routers.http-catchall-web_main.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_main.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      # catch HTTPS request on web_main only entrypoint (no need to catch HTTPS on web_main_secure)
      - "traefik.http.routers.http-catchall-web_main_secure.entrypoints=web_main"
      - "traefik.http.routers.http-catchall-web_main_secure.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-web_main_secure.priority=${ROUTER_PRIORITY_HTTP_TO_HTTPS_VALUE}"
      - "traefik.http.routers.http-catchall-web_main_secure.tls=true"
      
      # HTTP to HTTPS redirect middleware
      - "traefik.http.middlewares.redirect-web_main_secure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-web_main_secure.redirectscheme.permanent=true"
      - "traefik.http.middlewares.redirect-web_main_secure.redirectscheme.port=${NETWORK_PORT_MAIN_SECURE}"
      - "traefik.http.middlewares.redirect-web_secondary_secure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-web_secondary_secure.redirectscheme.permanent=true"
      - "traefik.http.middlewares.redirect-web_secondary_secure.redirectscheme.port=${NETWORK_PORT_SECONDARY_SECURE}"
      - "traefik.http.middlewares.redirect-web_admin_secure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-web_admin_secure.redirectscheme.permanent=true"
      - "traefik.http.middlewares.redirect-web_admin_secure.redirectscheme.port=${NETWORK_PORT_ADMIN_SECURE}"
      # to take care of websocket on HTTPS entrypoint
      - "traefik.http.middlewares.headers-secure.headers.customrequestheaders.X-Forwarded-Proto=https"
      # Auth middleware
      - 'traefik.http.middlewares.traefik_api_rest-auth.basicauth.users=${TRAEFIK_API_USER}:${TRAEFIK_API_HASH_PASSWORD}'
      # Security middleware
      # - "traefik.http.middlewares.security.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      # - "traefik.http.middlewares.security.headers.accesscontrolalloworiginlist=origin-list-or-null"
      # - "traefik.http.middlewares.security.headers.accesscontrolmaxage=100"
      # - "traefik.http.middlewares.security.headers.addvaryheader=true"
      # - "traefik.http.middlewares.security.headers.browserXssFilter=true"
      # - "traefik.http.middlewares.security.headers.contentTypeNosniff=true"
      # - "traefik.http.middlewares.security.headers.frameDeny=true"
      # - "traefik.http.middlewares.security.headers.customFrameOptionsValue=SAMEORIGIN"
      # - "traefik.http.middlewares.security.headers.referrerPolicy=same-origin"
      # - 'traefik.http.middlewares.security.headers.featurePolicy=vibrate "self"'
      # - "traefik.http.middlewares.security.headers.stsIncludeSubdomains=true"
      # - "traefik.http.middlewares.security.headers.stsPreload=true"
      # - "traefik.http.middlewares.security.headers.stsSeconds=315360000"
    networks:
      - default
    expose:
      # web_admin entrypoints
      - 9000
      - 9443
      # web_secondary entrypoints
      - 8000
      - 8443
      # web_main entrypoints
      - 80
      - 443
    ports:
      - ${NETWORK_PORT_MAIN}:80
      - ${NETWORK_PORT_MAIN_SECURE}:443
      - ${NETWORK_PORT_SECONDARY}:8000
      - ${NETWORK_PORT_SECONDARY_SECURE}:8443
      - ${NETWORK_PORT_ADMIN}:9000
      - ${NETWORK_PORT_ADMIN_SECURE}:9443
    command:
      # https://docs.traefik.io/reference/static-configuration/cli/
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--api.insecure=false"
      - "--global.sendAnonymousUsage=false"
      - "--entrypoints.web_main=true"
      - "--entrypoints.web_main.address=:80"
      #- "--entrypoints.web_main.http.middlewares=security@docker"
      - "--entrypoints.web_main_secure=true"
      - "--entrypoints.web_main_secure.address=:443"
      #- "--entrypoints.web_main_secure.http.middlewares=security@docker"
      - "--entrypoints.web_secondary=true"
      - "--entrypoints.web_secondary.address=:8000"
      #- "--entrypoints.web_secondary.http.middlewares=security@docker"
      - "--entrypoints.web_secondary_secure=true"
      - "--entrypoints.web_secondary_secure.address=:8443"
      #- "--entrypoints.web_secondary_secure.http.middlewares=security@docker"
      - "--entrypoints.web_admin=true"
      - "--entrypoints.web_admin.address=:9000"
      #- "--entrypoints.web_admin.http.middlewares=security@docker"
      - "--entrypoints.web_admin_secure=true"
      - "--entrypoints.web_admin_secure.address=:9443"
      #- "--entrypoints.web_admin_secure.http.middlewares=security@docker"
      - "--providers.rest=true"
      - "--providers.rest.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.constraints=Label(`${TANGO_INSTANCE_NAME}.managed`,`true`)"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/traefikconfig"
      - "--certificatesresolvers.tango=true"
      - "--certificatesresolvers.tango.acme.email=${LETS_ENCRYPT_MAIL}"
      - "--certificatesresolvers.tango.acme.storage=/letsencrypt/acme.json"


  # Traefik custom error pages : https://imandrea.me/blog/traefik-custom-404/
  # Custom error pages : https://github.com/tarampampam/error-pages
  error:
    image: tarampampam/error-pages:1.3.1
    container_name: ${TANGO_INSTANCE_NAME}_error
    restart: unless-stopped
    depends_on: 
      - service_init
    environment:
      # https://github.com/tarampampam/error-pages/tree/gh-pages
      TEMPLATE_NAME: ghost
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.services.error.loadbalancer.server.port=8080"

      - "traefik.http.middlewares.error-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-middleware.errors.service=error"
      - 'traefik.http.middlewares.error-middleware.errors.query=/{status}.html'

      # use as "fallback" for any request non matching any router (with priority below normal)
      # catch unresolved "unknown.domain.com" HTTP request on all entrypoints
      - "traefik.http.routers.error.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error.priority=${ERROR_PRIORITY}"
      - "traefik.http.routers.error.entrypoints=web_main,web_main_secure,web_admin,web_admin_secure,web_secondary,web_secondary_secure"
      - "traefik.http.routers.error.middlewares=error-middleware"
      # catch unresolved "unknown.domain.com" HTTPS request on all entrypoints
      - "traefik.http.routers.error-secure.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-secure.priority=${ERROR_PRIORITY}"
      - "traefik.http.routers.error-secure.entrypoints=web_main,web_main_secure,web_admin,web_admin_secure,web_secondary,web_secondary_secure"
      - "traefik.http.routers.error-secure.middlewares=error-middleware"
      - "traefik.http.routers.error-secure.tls=true"
      - "traefik.http.routers.error-secure.tls.domains[0].main=*.${TANGO_DOMAIN:-.*}"
      
    networks:
      - default
    expose:
      - 8080
