#!/usr/bin/env bash

# rebuild organizr2 associative array which are serialized in a special way into env file into ORGANIZR2_AUTH_GROUP_BY_SERVICE and ORGANIZR2_AUTH_GROUP_NAME_BY_ID env var
[ "${ORGANIZR2_AUTH_GROUP_BY_SERVICE}" = "" ] && declare -A ORGANIZR2_AUTH_GROUP_BY_SERVICE || eval declare -A ORGANIZR2_AUTH_GROUP_BY_SERVICE="${ORGANIZR2_AUTH_GROUP_BY_SERVICE}"
[ "${ORGANIZR2_AUTH_GROUP_NAME_BY_ID}" = "" ] && declare -A ORGANIZR2_AUTH_GROUP_NAME_BY_ID || eval declare -A ORGANIZR2_AUTH_GROUP_NAME_BY_ID="${ORGANIZR2_AUTH_GROUP_NAME_BY_ID}"

echo "---------==---- ${TANGO_APP_NAME_CAPS} SPECIFIC PATHS ----==---------"
echo Download path : [$DOWNLOAD_PATH] is mapped to {/download}
echo Plex transcode folder : [$PLEX_TRANSCODE_PATH]  {/transcode}
echo Vault folder for nzb/torrent watch folder [$VAULT_PATH] {/download/vault}
echo generic web folder \(including newsletters,...\) [$WEB_PATH] {/data/web}


echo "---------==---- AUTH SERVICES ----==---------"
echo " * ORGANIZR2 API"
__tmp="${ORGANIZR2_INSTANCE^^}_HTTP_URL_DEFAULT_SECURE"
echo L-- API endpoint : ${ORGANIZR2_API_URL}
echo L-- API documentation : ${!__tmp}/api/docs
echo L-- API version : ${ORGANIZR2_API_VERSION}
echo L-- API docker service instance : ${ORGANIZR2_INSTANCE}
echo " * ORGANIZR2 AUTH"
echo L-- manage mambo services authorization with organizr : $([ "${ORGANIZR2_AUTHORIZATION}" = "ON" ] && echo "ON" || echo "OFF")
# cannot launch docker client from a shell container
# echo "L-- organizr service status : $(docker inspect -f '{{ .State.Health.Status }}' ${TANGO_APP_NAME}_organizr2 )"
echo "L-- organizr groups list by id"
[ ${#ORGANIZR2_AUTH_GROUP_NAME_BY_ID[@]} -gt 0 ] && printf "  + "
for i in "${!ORGANIZR2_AUTH_GROUP_NAME_BY_ID[@]}";do printf "%s : %s | " "$i" "${ORGANIZR2_AUTH_GROUP_NAME_BY_ID[$i]}";done; printf "\n";
echo "L-- services (equivalent to organizr tab) : group authorized (group id)"
for i in "${!ORGANIZR2_AUTH_GROUP_BY_SERVICE[@]}";do _gid="${ORGANIZR2_AUTH_GROUP_BY_SERVICE[$i]}"; printf "  + %s : %s (%s)\n" "$i" "${ORGANIZR2_AUTH_GROUP_NAME_BY_ID[$_gid]}" "${_gid}";done;


