services:
  cloud9:
    image: sapk/cloud9:${CLOUD9_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_cloud9
    depends_on: 
      - service_init
    restart: unless-stopped
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : cloud9
      - "traefik.http.services.cloud9.loadbalancer.server.port=8181"
      - "traefik.http.services.cloud9.loadbalancer.server.scheme=http"
      - "traefik.http.services.cloud9.loadbalancer.passhostheader=true"
      # service router : cloud9
      - "traefik.http.routers.cloud9.entrypoints=${CLOUD9_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.cloud9.rule=HostRegexp(`{subdomain:${CLOUD9_SUBDOMAIN:-cloud9}}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.cloud9.priority=${CLOUD9_PRIORITY}"
      - "traefik.http.routers.cloud9.service=cloud9"
      - "traefik.http.routers.cloud9-secure.entrypoints=${CLOUD9_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.cloud9-secure.rule=HostRegexp(`{subdomain:${CLOUD9_SUBDOMAIN:-cloud9}}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.cloud9-secure.priority=${CLOUD9_PRIORITY}"
      - "traefik.http.routers.cloud9-secure.service=cloud9"
      - "traefik.http.routers.cloud9-secure.tls=true"
      - "traefik.http.routers.cloud9-secure.tls.domains[0].main=cloud9.${TANGO_DOMAIN:-.*}"
      # service router middlewares : whoami
      - "traefik.http.routers.cloud9.middlewares=error-middleware"
      - "traefik.http.routers.cloud9-secure.middlewares=error-middleware"
    networks:
      - default
    expose:
      - 8181
    command: >
      --auth ${CLOUD9_USERNAME:-}:${CLOUD9_PASSWORD:-}