services:
  # https://github.com/containous/whoami
  whoami:
    image: containous/whoami:${WHOAMI_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_whoami
    depends_on: 
      - service_init
    restart: unless-stopped
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=${WHOAMI_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.whoami.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami.priority=${WHOAMI_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami-secure.entrypoints=${WHOAMI_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.whoami-secure.rule=HostRegexp(`{subdomain:whoami}.{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.whoami-secure.service=whoami"
      - "traefik.http.routers.whoami-secure.tls=true"
      - "traefik.http.routers.whoami-secure.tls.domains[0].main=whoami.${TANGO_DOMAIN:-.*}"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.passhostheader=true"
    networks:
      - default
    expose:
      - 80