#########################################################################
# Title:         SABnzbd - Settings Tasks                               #
# Author(s):     desimaniac                                             #
# Modified by :  StudioEtrange
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Authorized dns name to request sabnzbd
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^host_whitelist\s?=.*'
    line: 'host_whitelist = "{{ sabnzbd.host_whitelist }}"'
    state: present

- name: Remove url_base
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^url_base\s?=.*'
    line: 'url_base = ""'
    state: present

# Authentication
- name: Set Username
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    insertafter: '^https_port\s?=.*'
    regexp: '^username\s?=.*'
    line: "username = {{ sabnzbd.user }}"
    state: present

- name: Set Password
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    insertbefore: '^bandwidth_max\s?=.*'
    regexp: '^password\s?=.*'
    line: "password = {{ sabnzbd.pass }}"
    state: present

- name: Set Form Auth
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^html_login\s?=.*'
    line: 'html_login = 1'
    state: present

# Paths
- name: Change incomplete downloads directory
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^download_dir\s?=.*'
    line: 'download_dir = /download/sabnzbd/incomplete'
    state: present

- name: Change complete downloads directory
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^complete_dir\s?=.*'
    line: 'complete_dir = /download/sabnzbd/complete'
    state: present

- name: Change watched directory
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^dirscan_dir\s?=.*'
    line: 'dirscan_dir = /vault/nzb'
    state: present

- name: Change script directory
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^script_dir\s?=.*'
    line: 'script_dir = /scripts'
    state: present

- name: Change logs directory
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^log_dir\s?=.*'
    line: 'log_dir = /config/logs'
    state: present


- name: Test if a servers section exist
  lineinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    regexp: '^\[servers\]'
    state: absent
  check_mode: yes
  changed_when: false
  register: servers_section

- name: Add a fake news server to bypass sabnzbd wizard
  blockinfile:
    path: "{{ sabnzbd_ini.stat.path }}"
    block: |
      [servers]
      [[fake.news.eu]]
      username = foo
      priority = 0
      enable = 0
      displayname = fake.news.eu
      name = fake.news.eu
      ssl_ciphers = ""
      notes = ""
      connections = 50
      ssl = 1
      host = fake.news.eu
      timeout = 60
      ssl_verify = 2
      send_group = 0
      password = bar
      optional = 1
      port = 563
      retention = 3400
  when: not servers_section.found
