#!/usr/bin/with-contenv bash




if [ ! -f /config/recently_added_books_section.html ]; then
    echo "> Installing default templates"
    cp /etc/templates/* /config/
fi

# Set Permissions
chown -R abc:abc \
	/app \
	/config \
	/newsletter