---
# medusa settings
- name: Set medusa username
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^web_username\s?=.*'
    line: 'web_username = "{{ medusa.user }}"'
    state: present

- name: Set medusa password
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^web_password\s?=.*'
    line: 'web_password = "{{ medusa.pass }}"'
    state: present

- name: Set medusa api_key
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^api_key\s?=.*'
    line: 'api_key = "{{ medusa.api_key }}"'
    state: present

- name: Do not check ssl
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^ssl_verify\s?=.*'
    line: 'ssl_verify = 0'
    state: present

- name: Do not launch_browser
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^launch_browser\s?=.*'
    line: 'launch_browser = 0'
    state: present

- name: Set post processing dir
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^tv_download_dir\s?=.*'
    line: 'tv_download_dir = /download/processdir/tv'
    state: present

- name: Set post processing method
  lineinfile:
    path: "{{ medusa_ini.stat.path }}"
    regexp: '^process_method\s?=.*'
    line: 'process_method = move'
    state: present
