---
- debug: 
    msg: "NZBTOMEDIA_DATA_PATH: {{ lookup('env','NZBTOMEDIA_DATA_PATH') }}"

- name: Register nzbtomedia_cfg
  stat:
    path: "{{ nzbtomedia.cfg }}"
  register: nzbtomedia_cfg

- name: Register sabnzbd_ini
  stat:
    path: "{{ sabnzbd.ini }}"
  register: sabnzbd_ini


- name: Settings sabznbd Tweaks
  include_tasks: "subtasks/nzbtomedia_sabnzbd_settings.yml"
  when: nzbtomedia_cfg.stat.exists and sabnzbd_ini.stat.exists